{% set name = "h3spark" %}
{% set version = "0.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/h3spark-{{ version }}.tar.gz
  sha256: 4d99f7467ff705502307c1688fc390733a8f0e221e81d09b66bc4fc8fd4d9ee6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - h3-py >=4.1,<4.2
    - pyspark >=3.0,<4.0

test:
  imports:
    - h3spark
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  dev_url: https://github.com/JosephChotard/h3spark
  home: https://github.com/JosephChotard/h3spark
  license_file: LICENSE
  license: MIT
  summary: Lightweight pyspark wrapper for h3-py

extra:
  recipe-maintainers:
    - JosephChotard
